// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaintenanceSystem.Models;

public partial class MaintenanceTasks
{
    public int Id { get; set; }

    public int? MachineId { get; set; }

    public int? MaintenanceId { get; set; }

    public DateTime? DueDate { get; set; }

    public int? DueOperationCount { get; set; }

    /// <summary>
    /// 1= on going, 2 = completed, 3 = skip
    /// </summary>
    public int? Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}